// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations;

[DbContext(typeof(ApplicationData))]
partial class ApplicationDataModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

        modelBuilder.Entity("Domain.Models.ManualProxy", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("DnsName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("TargetHostName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<ushort>("TargetPort")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("ManualProxies");
            });
#pragma warning restore 612, 618
    }
}
